name: pert_daily_planner
description: Daily tracker & planner with PERT-based time estimation, countdown alarms, streaks and calendar views.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  sqflite: ^2.3.3
  path: ^1.9.0
  uuid: ^4.4.2
  intl: ^0.19.0
  table_calendar: ^3.1.2
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  flutter_timezone: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
